# Analise_dados_cadastrais_cvm - 
## Este notebook estuda um dataset da CVM, afim de praticar o DataWragling, ou seja, o tratamento dos dados

### Site:       https://filipe-deabreu.com

### Autor:      Filipe de Abreu

### Manutenção:  Filipe de Abreu

<hr>

# Testado em
### OS: Windows 11                                      
### Versão do python: 3.12.7

In [10]:
#importações 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import chardet

In [158]:
#Foi necessario utilizar a biblioteca chardet para detectar o tipo de encoding do arquivo, pois a biblioteca pandas estava falha em ler o arquivo

with open("datasets/CVM Dados Cadastrais.csv", "rb") as file:
    result = chardet.detect(file.read())
    print(result)  # Shows the detected encoding
    encoding = result['encoding']

{'encoding': 'ISO-8859-1', 'confidence': 0.7271107292265566, 'language': ''}

In [159]:
df = pd.read_csv('datasets/CVM Dados Cadastrais.csv', sep=';', encoding=encoding)
df

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A.,2W ECOBANK S.A.,2020-10-29,2007-03-23,NaN,NaN,ATIVO,2020-10-29,25224,...,SP,NaN,4707000.0,11,39579400.0,NaN,NaN,ri@2wenergia.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,NaN,20020000.0,21,22338867.0,21.0,22338867.0,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,12.091.809/0001-55,3R PETROLEUM OLÉO E GÁS S.A.,NaN,2020-11-09,2010-06-08,NaN,NaN,ATIVO,2020-11-09,25291,...,RJ,NaN,22250180.0,21,21455555.0,0.0,0.0,ri@3rpetroleum.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
3,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaN,NaN,ATIVO,1997-07-11,16330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.596.945/0001-83,BAKER TILLY 4PARTNERS AUDITORES INDEPENDENTES S/S
4,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,NaN,NaN,ATIVO,1997-05-30,16284,...,RJ,NaN,20020010.0,21,38043700.0,0.0,0.0,gar@opportunity.com.br,40.262.602/0001-31,"BKR - LOPES, MACHADO AUDITORES"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2566,13.574.594/0001-96,ZAMP S.A.,ZAMP S.A.,2017-12-14,2011-04-06,NaN,NaN,ATIVO,2017-12-14,24317,...,NaN,NaN,6455020.0,11,23970320.0,0.0,0.0,ri@burgerking.com.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2567,71.320.931/0001-15,ZANINI SA EQUIPS PESADOS,ZANINI,1971-07-05,NaN,1997-01-27,ATENDIMENTO AS NORMAS DA INSTR CVM 03/78,CANCELADA,1997-01-27,11835,...,SP,NaN,1013000.0,11,6424066.0,11.0,NaN,NaN,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2568,24.744.012/0001-99,ZH OPERAÇÕES S/A,ZH OPERAÇÕES S/A,2016-09-16,2016-04-15,2017-08-07,Cancelamento de ofício - IN CVM 480/09,CANCELADA,2017-08-07,24007,...,SP,NaN,4609005.0,011,50548989.0,NaN,NaN,renno@setaatacadista.com.br,00.115.909/0001-95,MS AUDITORES INDEPENDENTES S/C
2569,92.749.217/0001-17,ZIVI SA CUTELARIA,ZIVI S/A,1968-11-01,1931-01-01,2003-12-29,ELISÃO POR INCORPORAÇÃO,CANCELADA,2003-12-29,11843,...,RS,NaN,91030530.0,51,33585109.0,51.0,33585176.0,michael.ceitlin@gem.ind.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2570,74.533.787/0001-93,ZOGBI LEASING S/A ARRENDAMENTO MERCANTIL,ZOGBI LEASING,1997-09-18,1993-06-18,2004-12-23,ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02,CANCELADA,2004-12-23,16462,...,NaN,NaN,6029900.0,11,36814011.0,11.0,36844630.0,4000.isola@bradesco.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [160]:
#Formato do dataframe e informações básicas
print(f'Numero de observações : {df.shape[0]} \nNumero de variaveis {df.shape[1]}')
df.info()

Numero de observações : 2571
Numero de variaveis 47
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2571 entries, 0 to 2570
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CNPJ_CIA            2571 non-null   object
 1   DENOM_SOCIAL        2571 non-null   object
 2   DENOM_COMERC        2483 non-null   object
 3   DT_REG              2571 non-null   object
 4   DT_CONST            1642 non-null   object
 5   DT_CANCEL           1784 non-null   object
 6   MOTIVO_CANCEL       1782 non-null   object
 7   SIT                 2571 non-null   object
 8   DT_INI_SIT          2571 non-null   object
 9   CD_CVM              2571 non-null   int64
 10  SETOR_ATIV          2565 non-null   object
 11  TP_MERC             668 non-null    object
 12  CATEG_REG           1331 non-null   object
 13  DT_INI_CATEG        1331 non-null   object
 14  SIT_EMISSOR         1241 non-null   object
 15  DT_INI_SIT_EMISSOR  1241 non-null   object
 16  CONTROLE_ACIONARIO  2569 non-null   object
 17  TP_ENDER            2570 non-null   object
 18  LOGRADOURO          2570 non-null   object
 19  COMPL               1393 non-null   object
 20  BAIRRO              1926 non-null   object
 21  MUN                 2563 non-null   object
 22  UF                  2570 non-null   object
 23  PAIS                2495 non-null   object
 24  CEP                 2569 non-null   float64
 25  DDD_TEL             2551 non-null   float64
 26  TEL                 2551 non-null   float64
 27  DDD_FAX             1802 non-null   float64
 28  FAX                 1815 non-null   float64
 29  EMAIL               1677 non-null   object
 30  TP_RESP             2502 non-null   object
 31  RESP                2501 non-null   object
 32  DT_INI_RESP         2502 non-null   object
 33  LOGRADOURO_RESP     2499 non-null   object
 34  COMPL_RESP          1343 non-null   object
 35  BAIRRO_RESP         1804 non-null   object
 36  MUN_RESP            2499 non-null   object
 37  UF_RESP             2443 non-null   object
 38  PAIS_RESP           26 non-null     object
 39  CEP_RESP            2497 non-null   float64
 40  DDD_TEL_RESP        2496 non-null   object
 41  TEL_RESP            2495 non-null   float64
 42  DDD_FAX_RESP        2415 non-null   float64
 43  FAX_RESP            1876 non-null   float64
 44  EMAIL_RESP          1671 non-null   object
 45  CNPJ_AUDITOR        2471 non-null   object
 46  AUDITOR             2471 non-null   object
dtypes: float64(9), int64(1), object(37)
memory usage: 944.2+ KB

In [161]:
#Após verificar as primeiras impressões, constatou-se uma grande quantidade de dados nulos, mas será necessario avaliar quanto exatamenteD
#Aqui um dicionario que cotem todas as variaveis do dataframe como chave e como valor contem a contagem de dados nulos

dici = {}

for i in df.columns:
    dici[i] = len(df[i][df[i].isna() == True])

dici

{'CNPJ_CIA': 0,
 'DENOM_SOCIAL': 0,
 'DENOM_COMERC': 88,
 'DT_REG': 0,
 'DT_CONST': 929,
 'DT_CANCEL': 787,
 'MOTIVO_CANCEL': 789,
 'SIT': 0,
 'DT_INI_SIT': 0,
 'CD_CVM': 0,
 'SETOR_ATIV': 6,
 'TP_MERC': 1903,
 'CATEG_REG': 1240,
 'DT_INI_CATEG': 1240,
 'SIT_EMISSOR': 1330,
 'DT_INI_SIT_EMISSOR': 1330,
 'CONTROLE_ACIONARIO': 2,
 'TP_ENDER': 1,
 'LOGRADOURO': 1,
 'COMPL': 1178,
 'BAIRRO': 645,
 'MUN': 8,
 'UF': 1,
 'PAIS': 76,
 'CEP': 2,
 'DDD_TEL': 20,
 'TEL': 20,
 'DDD_FAX': 769,
 'FAX': 756,
 'EMAIL': 894,
 'TP_RESP': 69,
 'RESP': 70,
 'DT_INI_RESP': 69,
 'LOGRADOURO_RESP': 72,
 'COMPL_RESP': 1228,
 'BAIRRO_RESP': 767,
 'MUN_RESP': 72,
 'UF_RESP': 128,
 'PAIS_RESP': 2545,
 'CEP_RESP': 74,
 'DDD_TEL_RESP': 75,
 'TEL_RESP': 76,
 'DDD_FAX_RESP': 156,
 'FAX_RESP': 695,
 'EMAIL_RESP': 900,
 'CNPJ_AUDITOR': 100,
 'AUDITOR': 100}

In [162]:
df_isna = pd.DataFrame(dici.values(), index = dici.keys(), columns=['Valores_Faltantes']) #Cria um dataframe utilizando as chaves do dicionario como index
#E os valores do dicionario como obersações

df_isna['Valores_faltantes_relativos'] = np.round((df_isna['Valores_Faltantes'] / df.shape[0]) * 100, decimals = 2) #Cria uma nova variavel
#Os valores dessa nova variavel sao dividios pelo numero total de obserções do dataframe original e multiplicados por 100

#Ordena os valores com base na variabel 'Valores_Faltantes' em ordem decrescente
df_isna.sort_values(by='Valores_Faltantes', ascending = False)

#A variavel valores faltantes relativos indica em porcentagem a quantidade de dados nulos (ou NaN)
#Assim fica bem visível que no dataframe original, temos variaveis com 98% dos dados valtantes,
#Assim, tenho por mim que variaveis com tantos valores nulo nao podem ser analisados

                    Valores_Faltantes  Valores_faltantes_relativos
PAIS_RESP                        2545                        98.99
TP_MERC                          1903                        74.02
DT_INI_SIT_EMISSOR               1330                        51.73
SIT_EMISSOR                      1330                        51.73
CATEG_REG                        1240                        48.23
DT_INI_CATEG                     1240                        48.23
COMPL_RESP                       1228                        47.76
COMPL                            1178                        45.82
DT_CONST                          929                        36.13
EMAIL_RESP                        900                        35.01
EMAIL                             894                        34.77
MOTIVO_CANCEL                     789                        30.69
DT_CANCEL                         787                        30.61
DDD_FAX                           769                        29.91
BAIRRO_RESP                       767                        29.83
FAX                               756                        29.40
FAX_RESP                          695                        27.03
BAIRRO                            645                        25.09
DDD_FAX_RESP                      156                         6.07
UF_RESP                           128                         4.98
CNPJ_AUDITOR                      100                         3.89
AUDITOR                           100                         3.89
DENOM_COMERC                       88                         3.42
TEL_RESP                           76                         2.96
PAIS                               76                         2.96
DDD_TEL_RESP                       75                         2.92
CEP_RESP                           74                         2.88
MUN_RESP                           72                         2.80
LOGRADOURO_RESP                    72                         2.80
RESP                               70                         2.72
TP_RESP                            69                         2.68
DT_INI_RESP                        69                         2.68
TEL                                20                         0.78
DDD_TEL                            20                         0.78
MUN                                 8                         0.31
SETOR_ATIV                          6                         0.23
CONTROLE_ACIONARIO                  2                         0.08
CEP                                 2                         0.08
LOGRADOURO                          1                         0.04
UF                                  1                         0.04
TP_ENDER                            1                         0.04
DENOM_SOCIAL                        0                         0.00
CD_CVM                              0                         0.00
DT_INI_SIT                          0                         0.00
SIT                                 0                         0.00
DT_REG                              0                         0.00
CNPJ_CIA                            0                         0.00

In [163]:
#Com base nos meus próprios critério, irei remover do dataframe original, todas as variveis que possuem valores faltantes maior do que 50% 
#Com base no dataframe acima, eu poderia de dropar manualmente derrubar as 4 primeiras variaveis
#Mais seria interessante criar uma lógica que fizesse isso, pois poderia ser um banco de dados com milhares de variaveis

#
print(f'Numero de colunas antes do drop {df.shape[1]}\n')

for i in df.columns:
    if (len(df[i][df[i].isna() == True]) / df.shape[0]) * 100 > 50.0:
        del df[i]

print(f'Numero de colunas depois do drop {df.shape[1]}')


#Conforme espera, 4 variaveis foram removidas do dataframe

Numero de colunas antes do drop 47

Numero de colunas depois do drop 43

In [209]:
#Test para substituição de observações com valores NaN por qualquer outro valor
#Neste caso, utilizarei a variavel onde armazenam valores de email
#Conforme observações anterior, a variavel apresenta uma quantidade 35% de valores NAn

#Selectionando e substituindo todos os falores NaN por 'noemail@noemail.com'
df['EMAIL_RESP'][df['EMAIL_RESP'].isna() == True] = 'noemail@noemail.com'
df

C:\Users\FIlipe Queiroz\AppData\Local\Temp\ipykernel_6608\3493768512.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EMAIL_RESP'][df['EMAIL_RESP'].isna() == True] = 'noemail@noemail.com'

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,MUN_RESP,UF_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A.,2W ECOBANK S.A.,2020-10-29,2007-03-23,NaN,NaN,ATIVO,2020-10-29,25224,...,SÃO PAULO,SP,4707000.0,11,39579400.0,NaN,NaN,ri@2wenergia.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RIO DE JANEIRO,RJ,20020000.0,21,22338867.0,21.0,22338867.0,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,12.091.809/0001-55,3R PETROLEUM OLÉO E GÁS S.A.,NaN,2020-11-09,2010-06-08,NaN,NaN,ATIVO,2020-11-09,25291,...,RIO DE JANEIRO,RJ,22250180.0,21,21455555.0,0.0,0.0,ri@3rpetroleum.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
3,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaN,NaN,ATIVO,1997-07-11,16330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,noemail@noemail.com,18.596.945/0001-83,BAKER TILLY 4PARTNERS AUDITORES INDEPENDENTES S/S
4,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,NaN,NaN,ATIVO,1997-05-30,16284,...,RIO DE JANEIRO,RJ,20020010.0,21,38043700.0,0.0,0.0,gar@opportunity.com.br,40.262.602/0001-31,"BKR - LOPES, MACHADO AUDITORES"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2566,13.574.594/0001-96,ZAMP S.A.,ZAMP S.A.,2017-12-14,2011-04-06,NaN,NaN,ATIVO,2017-12-14,24317,...,BARUERI,NaN,6455020.0,11,23970320.0,0.0,0.0,ri@burgerking.com.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2567,71.320.931/0001-15,ZANINI SA EQUIPS PESADOS,ZANINI,1971-07-05,NaN,1997-01-27,ATENDIMENTO AS NORMAS DA INSTR CVM 03/78,CANCELADA,1997-01-27,11835,...,SÃO PAULO,SP,1013000.0,11,6424066.0,11.0,NaN,noemail@noemail.com,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2568,24.744.012/0001-99,ZH OPERAÇÕES S/A,ZH OPERAÇÕES S/A,2016-09-16,2016-04-15,2017-08-07,Cancelamento de ofício - IN CVM 480/09,CANCELADA,2017-08-07,24007,...,SÃO PAULO,SP,4609005.0,011,50548989.0,NaN,NaN,renno@setaatacadista.com.br,00.115.909/0001-95,MS AUDITORES INDEPENDENTES S/C
2569,92.749.217/0001-17,ZIVI SA CUTELARIA,ZIVI S/A,1968-11-01,1931-01-01,2003-12-29,ELISÃO POR INCORPORAÇÃO,CANCELADA,2003-12-29,11843,...,PORTO ALEGRE,RS,91030530.0,51,33585109.0,51.0,33585176.0,michael.ceitlin@gem.ind.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2570,74.533.787/0001-93,ZOGBI LEASING S/A ARRENDAMENTO MERCANTIL,ZOGBI LEASING,1997-09-18,1993-06-18,2004-12-23,ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02,CANCELADA,2004-12-23,16462,...,OSASCO,NaN,6029900.0,11,36814011.0,11.0,36844630.0,4000.isola@bradesco.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [214]:
#Cruzando dados
np.round(
    pd.crosstab(df['MOTIVO_CANCEL'], 
                df['SIT'], #Selecionando as variaveis a serem cruzadas
                normalize=True).sort_values(by='CANCELADA',  #Ordenando pela coluna 'CANCELADA' em ordem decrescente
                                            ascending=False) * 100 
)

#È possivel contar dessa forma pois só existe valore na coluna 'MOTIVO_CANCEl' quando 'SIT' é "CANCELADA"
#lOGO, se cancelada, existe um motivo de cancelamento, nao as observações cujo o valor seja 'ativo', nao entram para a conta

SIT                                                 CANCELADA
MOTIVO_CANCEL
Cancelamento Voluntário - IN CVM 480/09                  16.0
ELISÃO POR INCORPORAÇÃO                                  15.0
ATENDIMENTO AS NORMAS DA INSTR CVM 03/78                 14.0
ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02         12.0
CANCELAMENTO DE OFÍCIO C/BASE INSTR. CVM 287/98          11.0
ATENDIMENTO AS NORMAS DA INSTR CVM 229/95                10.0
Cancelamento de ofício - IN CVM 480/09                    7.0
ENQUADRAMENTO EXCEÇÕES DA INSTR. CVM 03/78                6.0
Migração de Registro (Resolução n° 60)                    3.0
ELISÃO POR LIQUIDAÇÃO                                     1.0
INCORPORAÇÃO                                              1.0
ELISÃO POR EXTINÇÃO DA CIA                                1.0
ELISÃO POR TRANSFORMAÇÃO                                  1.0
CANCELAMENTO OFICIO COM BASE INSTR. CVM 29/84             1.0
CANCELAMENTO A PEDIDO - artigo 14, I Resolução ...        0.0
ENQUADRAMENTO HIPÓTESE ESTAB P/ COML EM 29/10/79          0.0
LIQUIDAÇÃO EXTRAJUDICIAL                                  0.0
CANCELAMENTO A PEDIDO                                     0.0
ELISÃO DEVIDO A CANCELAMENTO DO RPJ PELO BACEN            0.0

In [226]:
#Cruzando dados para verificar a quantidade de empresas por 'SIT' (SITUAÇÃO)
df.groupby('SIT').size()

#Verificado que a situação 'SUSPENSO(A) - DECISÃO ADM' possui apenas uma obervação, o que chama a atenção

SIT
ATIVO                         786
CANCELADA                    1784
SUSPENSO(A) - DECISÃO ADM       1
dtype: int64

In [230]:
#Verificando qual a unica obserção onde a variavel 'SIT' tem o valor 'SUSPENSO(A) - DECISÃO ADM'
df[df['SIT'] == 'SUSPENSO(A) - DECISÃO ADM']

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,MUN_RESP,UF_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
1193,14.333.683/0001-03,FONTAINE VILLE PARTICIPAÇÕES S/A,FONTAINE VILLE PARTICIPAÇÕES S/A,2013-01-16,2011-03-18,NaN,NaN,SUSPENSO(A) - DECISÃO ADM,2022-11-10,23019,...,SÃO PAULO,SP,4552020.0,11,45503410.0,11.0,45503410.0,administrativo.financeiro@fontaineville.com,13.026.685/0001-97,EVOLUÇÃO AUDITORES INDEPENDENTES S/S ILIMITADA

In [246]:
#Verificando os municipios on mais se existem mais empresas com o situação CANCELADA
pd.crosstab(
    df['SIT'],
    df['MUN_RESP']
).T.head(30).sort_values(by='CANCELADA', ascending=False).drop(columns=['SUSPENSO(A) - DECISÃO ADM'])

SIT                      ATIVO  CANCELADA
MUN_RESP
BELO HORIZONTE              29         53
BARUERI                     11         22
BRASÍLIA                    15         15
BELÉM                        3         10
BLUMENAU                     4          8
CAMAÇARI                     2          5
CAMPINA GRANDE               0          3
ARACAJU                      1          2
CAJAMAR                      0          2
BRUSQUE                      2          2
BENTO GONÇALVES              1          1
CAMBÉ                        0          1
AMERICANA                    0          1
CACHOEIRINHA                 2          1
CABREÚVA                     0          1
CABO DE SANTO AGOSTINHO      0          1
AMÉLIA RODRIGUES             0          1
ANANINDEUA                   0          1
ABREU E LIMA                 0          1
ARRAIAL DO CABO              0          1
APARECIDA DE GOIÂNIA         1          1
ALVORADA                     0          1
BAGÉ                         0          1
BACABAL                      0          1
ASTOLFO DUTRA                0          1
ASSIS                        0          1
ARUJÁ                        0          1
BAURU                        3          0
ATIBAIA                      1          0
ANÁPOLIS                     2          0

In [337]:
#Verificando agora os setores de atividades
df['SETOR_ATIV'].unique()

array(['Energia Elétrica', 'Securitização de Recebíveis',
       'Petróleo e Gás', 'Emp. Adm. Part. - Energia Elétrica',
       'Emp. Adm. Part. - Sem Setor Principal', 'Emp. Adm. Participações',
       'Máquinas, Equipamentos, Veículos e Peças',
       'Comércio (Atacado e Varejo)', 'Arrendamento Mercantil',
       'Gráficas e Editoras',
       'Emp. Adm. Part. - Const. Civil, Mat. Const. e Decoração',
       'Metalurgia e Siderurgia', 'Petroquímicos e Borracha',
       'Agricultura (Açúcar, Álcool e Cana)', 'Farmacêutico e Higiene',
       'Saneamento, Serv. Água e Gás', 'Serviços Diversos',
       'Seguradoras e Corretoras',
       'Construção Civil, Mat. Constr. e Decoração',
       'Emp. Adm. Part. - Serviços Transporte e Logística',
       'Outras Atividades Industriais',
       'Emp. Adm. Part. - Intermediação Financeira', 'Têxtil e Vestuário',
       'Telecomunicações',
       'Emp. Adm. Part. - Comércio (Atacado e Varejo)',
       'Serviços Transporte e Logística',
       'Emp. Adm. Part. - Seguradoras e Corretoras', 'Bancos',
       'Hospedagem e Turismo', 'Bebidas e Fumo', 'Serviços Médicos',
       'Emp. Adm. Part. - Têxtil e Vestuário', 'Alimentos',
       'Emp. Adm. Part. - Educação', 'Educação', 'Brinquedos e Lazer',
       'Papel e Celulose', 'Extração Mineral',
       'Emp. Adm. Part. - Telecomunicações',
       'Emp. Adm. Part. - Serviços médicos',
       'Emp. Adm. Part. - Comunicação e Informática',
       'Emp. Adm. Part. - Extração Mineral',
       'Bolsas de Valores/Mercadorias e Futuros', 'Crédito Imobiliário',
       'Intermediação Financeira', nan, 'Embalagens',
       'Emp. Adm. Part. - Crédito Imobiliário',
       'Comunicação e Informática',
       'Emp. Adm. Part. - Hospedagem e Turismo', 'Comércio Exterior',
       'Emp. Adm. Part. - Bancos', 'Emp. Adm. Part. - Alimentos',
       'Emp. Adm. Part. - Saneamento, Serv. Água e Gás',
       'Emp. Adm. Part.-Bolsas de Valores/Mercadorias e Futuros',
       'Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças',
       'Emp. Adm. Part. - Metalurgia e Siderurgia',
       'Emp. Adm. Part. - Petróleo e Gás', 'Pesca',
       'Emp. Adm. Part. - Agricultura (Açúcar, Álcool e Cana)',
       'Emp. Adm. Part. - Securitização de Recebíveis',
       'Emp. Adm. Part. - Petroquímicos e Borracha',
       'Emp. Adm. Part. - Arrendamento Mercantil', 'Reflorestamento',
       'Emp. Adm. Part. - Embalagens',
       'Emp. Adm. Part. - Farmacêutico e Higiene',
       'Emp. Adm. Part. - Gráficas e Editoras', 'Factoring',
       'Emp. Adm. Part. - Brinquedos e Lazer',
       'Emp. Adm. Part. - Papel e Celulose', 'Serviços em Geral'],
      dtype=object)

In [342]:
#Ao identificar um certo padrao de forma visual, onde a muitos valores que começam com Emp, decidi verificar quais sao todos os valores que possuem 
# esse padrao

serie = pd.Series(df['SETOR_ATIV'].unique())
select = serie.str.startswith('Emp')
serie[select]

#Obtive um error informando que existe valores NaN na selecao, algo que nao havia verificado visualmente

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [343]:
#confirmando a existencia do valor NaN
serie[serie.isna()]

45    NaN
dtype: object

In [341]:
#Dupla confirmação de existencia do valor NaN
pd.DataFrame(serie, columns=['valores']).iloc[45:46:,0]

45    NaN
Name: valores, dtype: object

In [370]:
#Após a descoberta do valor NaN, feito a correta seleção
serie2 = serie[serie.isna() == False]
select2 = serie2.str.startswith('Emp') #Filtrando as observações que começam com 'EMP' e armazenando essa selecação 
setores_emp = serie2[select2].reset_index().drop(columns=['index']).rename(
            columns = {0:'Valor que começam com `Emp`'}
        )
setores_emp

# se identifica 31 observações que começam com 'Emp'

                          Valor que começam com `Emp`
0                  Emp. Adm. Part. - Energia Elétrica
1               Emp. Adm. Part. - Sem Setor Principal
2                             Emp. Adm. Participações
3   Emp. Adm. Part. - Const. Civil, Mat. Const. e ...
4   Emp. Adm. Part. - Serviços Transporte e Logística
5          Emp. Adm. Part. - Intermediação Financeira
6       Emp. Adm. Part. - Comércio (Atacado e Varejo)
7          Emp. Adm. Part. - Seguradoras e Corretoras
8                Emp. Adm. Part. - Têxtil e Vestuário
9                          Emp. Adm. Part. - Educação
10                 Emp. Adm. Part. - Telecomunicações
11                 Emp. Adm. Part. - Serviços médicos
12        Emp. Adm. Part. - Comunicação e Informática
13                 Emp. Adm. Part. - Extração Mineral
14              Emp. Adm. Part. - Crédito Imobiliário
15             Emp. Adm. Part. - Hospedagem e Turismo
16                           Emp. Adm. Part. - Bancos
17                        Emp. Adm. Part. - Alimentos
18     Emp. Adm. Part. - Saneamento, Serv. Água e Gás
19  Emp. Adm. Part.-Bolsas de Valores/Mercadorias ...
20     Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças
21          Emp. Adm. Part. - Metalurgia e Siderurgia
22                   Emp. Adm. Part. - Petróleo e Gás
23  Emp. Adm. Part. - Agricultura (Açúcar, Álcool ...
24      Emp. Adm. Part. - Securitização de Recebíveis
25         Emp. Adm. Part. - Petroquímicos e Borracha
26           Emp. Adm. Part. - Arrendamento Mercantil
27                       Emp. Adm. Part. - Embalagens
28           Emp. Adm. Part. - Farmacêutico e Higiene
29              Emp. Adm. Part. - Gráficas e Editoras
30               Emp. Adm. Part. - Brinquedos e Lazer
31                 Emp. Adm. Part. - Papel e Celulose

In [369]:
#Verificando os 10 setores de atividade com maior quantidade de observações
pd.DataFrame(df[['SETOR_ATIV']].value_counts()).head(10)

                                            count
SETOR_ATIV
Máquinas, Equipamentos, Veículos e Peças      178
Construção Civil, Mat. Constr. e Decoração    167
Emp. Adm. Participações                       156
Securitização de Recebíveis                   141
Metalurgia e Siderurgia                       139
Serviços Transporte e Logística               126
Têxtil e Vestuário                            122
Bancos                                        115
Alimentos                                     110
Energia Elétrica                              110

In [387]:
#Aproveitando as informações de um setor anterior, onde eu verificar todas as observações que começão com EMP
#Realize a mesma contagem utilizando essa informação

contagem = pd.DataFrame(df[['SETOR_ATIV']].value_counts())
contagem = contagem.reset_index()
contagem[contagem['SETOR_ATIV'].isin(list(setores_emp.iloc[:, 0]))]

                                           SETOR_ATIV  count
2                             Emp. Adm. Participações    156
11              Emp. Adm. Part. - Sem Setor Principal    106
17                 Emp. Adm. Part. - Energia Elétrica     47
18                 Emp. Adm. Part. - Telecomunicações     39
21  Emp. Adm. Part. - Serviços Transporte e Logística     33
23  Emp. Adm. Part. - Const. Civil, Mat. Const. e ...     26
30      Emp. Adm. Part. - Comércio (Atacado e Varejo)     20
33         Emp. Adm. Part. - Intermediação Financeira     14
35                   Emp. Adm. Part. - Petróleo e Gás     12
37                 Emp. Adm. Part. - Extração Mineral     11
39     Emp. Adm. Part. - Máqs., Equip., Veíc. e Peças      8
40          Emp. Adm. Part. - Metalurgia e Siderurgia      8
41                         Emp. Adm. Part. - Educação      8
43     Emp. Adm. Part. - Saneamento, Serv. Água e Gás      7
44         Emp. Adm. Part. - Seguradoras e Corretoras      6
45                 Emp. Adm. Part. - Serviços médicos      6
49               Emp. Adm. Part. - Têxtil e Vestuário      5
50        Emp. Adm. Part. - Comunicação e Informática      5
51                        Emp. Adm. Part. - Alimentos      5
52         Emp. Adm. Part. - Petroquímicos e Borracha      5
53             Emp. Adm. Part. - Hospedagem e Turismo      5
54              Emp. Adm. Part. - Crédito Imobiliário      5
57      Emp. Adm. Part. - Securitização de Recebíveis      4
59               Emp. Adm. Part. - Brinquedos e Lazer      3
60           Emp. Adm. Part. - Arrendamento Mercantil      2
61  Emp. Adm. Part. - Agricultura (Açúcar, Álcool ...      2
62           Emp. Adm. Part. - Farmacêutico e Higiene      2
63                       Emp. Adm. Part. - Embalagens      2
66                 Emp. Adm. Part. - Papel e Celulose      1
67              Emp. Adm. Part. - Gráficas e Editoras      1
68  Emp. Adm. Part.-Bolsas de Valores/Mercadorias ...      1
69                           Emp. Adm. Part. - Bancos      1