In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import shap
from pandasql import sqldf

In [37]:
df = pd.read_csv(
    'Meu_Municipio_Cobertura.csv',
    sep=';'
)

df.head(30)

,Ano,Mês,Operadora,Tecnologia,Código IBGE,Município,UF,Nome UF,Região,Código Nacional,% moradores cobertos,% domicílios cobertos,% área coberta
0,2021.0,11.0,Todas,4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"99,911338304165","99,910746714728","91,859948680187"
1,2021.0,11.0,LIGUE,2G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
2,2021.0,11.0,VIVO,2G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"95,647555982772","95,959903169683","66,267932616656"
3,2021.0,11.0,LIGUE,3G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
4,2021.0,11.0,CLARO,Todas,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"99,486127766182","99,532104273336","82,804391686534"
5,2021.0,11.0,SERCOMTEL,4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
6,2021.0,11.0,SERCOMTEL,Todas,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
7,2021.0,11.0,LIGUE,3G4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
8,2021.0,11.0,VIVO,Todas,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"99,659911044447","99,668570130315","83,879952754244"
9,2021.0,11.0,VIVO,3G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"99,564145483379","99,57622047023","80,562800846473"
10,2021.0,11.0,ALGAR,5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
11,2021.0,11.0,LIGUE,4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
12,2021.0,11.0,Todas,5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
13,2021.0,11.0,NEXTEL,3G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"88,710965977656","89,366081734065","41,949408731488"
14,2021.0,11.0,SERCOMTEL,2G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
15,2021.0,11.0,CLARO,5G_SA_NSA,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
16,2021.0,11.0,NEXTEL,5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
17,2021.0,11.0,ALGAR,Todas,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
18,2021.0,11.0,Todas,4G5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
19,2021.0,11.0,TIM,4G5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
20,2021.0,11.0,LIGUE,5G_SA_NSA,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
21,2021.0,11.0,ALGAR,5G_SA_NSA,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
22,2021.0,11.0,TIM,3G4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"99,814454680841","99,818310637533","86,691198243296"
23,2021.0,11.0,TIM,2G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"93,734914715251","93,977498572324","58,193558178732"
24,2021.0,11.0,SERCOMTEL,3G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
25,2021.0,11.0,NEXTEL,Todas,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,"88,710965977656","89,366081734065","41,949408731488"
26,2021.0,11.0,ALGAR,3G4G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
27,2021.0,11.0,LIGUE,5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
28,2021.0,11.0,VIVO,5G_SA_NSA,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0
29,2021.0,11.0,OI,5G,4115200.0,Maringá - PR,PR,Paraná,Sul,44.0,0,0,0

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515041 entries, 0 to 1515040
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Ano                    1515040 non-null  float64
 1   Mês                    1515040 non-null  float64
 2   Operadora              1515040 non-null  object
 3   Tecnologia             1515040 non-null  object
 4   Código IBGE            1515040 non-null  float64
 5   Município              1515040 non-null  object
 6   UF                     1515040 non-null  object
 7   Nome UF                1515040 non-null  object
 8   Região                 1515040 non-null  object
 9   Código Nacional        1515040 non-null  float64
 10  % moradores cobertos   1513680 non-null  object
 11  % domicílios cobertos  1513680 non-null  object
 12  % área coberta         1513680 non-null  object
dtypes: float64(4), object(9)
memory usage: 150.3+ MB

In [55]:
df.columns

Index(['Ano', 'Mês', 'Operadora', 'Tecnologia', 'Código IBGE', 'Município',
       'UF', 'Nome UF', 'Região', 'Código Nacional', '% moradores cobertos',
       '% domicílios cobertos', '% área coberta'],
      dtype='object')

In [95]:
df.describe()

,Ano,Mês,Código IBGE,Código Nacional,% moradores cobertos,% domicílios cobertos,% área coberta
count,1.515040e+06,1.515040e+06,1.515040e+06,1.515040e+06,1.513680e+06,1.513680e+06,1.513680e+06
mean,2.022441e+03,8.911765e+00,3.253591e+06,5.709964e+01,2.050808e+01,2.067536e+01,9.908949e+00
std,1.116486e+00,3.450216e+00,9.848222e+05,2.542054e+01,3.480325e+01,3.498771e+01,2.245501e+01
min,2.021000e+03,3.000000e+00,1.100015e+06,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.021000e+03,9.000000e+00,2.512101e+06,3.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.022000e+03,1.100000e+01,3.146280e+06,5.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.023000e+03,1.200000e+01,4.119202e+06,8.200000e+01,4.162521e+01,4.297516e+01,3.221171e+00
max,2.024000e+03,1.200000e+01,5.300108e+06,9.900000e+01,1.000000e+02,1.000000e+02,1.000000e+02

In [69]:
df['% moradores cobertos'] = df['% moradores cobertos'].str.replace(',', '.').astype(float)
df['% domicílios cobertos'] = df['% domicílios cobertos'].str.replace(',', '.').astype(float)
df['% área coberta'] = df['% área coberta'].str.replace(',', '.').astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515041 entries, 0 to 1515040
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Ano                    1515040 non-null  float64
 1   Mês                    1515040 non-null  float64
 2   Operadora              1515040 non-null  object
 3   Tecnologia             1515040 non-null  object
 4   Código IBGE            1515040 non-null  float64
 5   Município              1515040 non-null  object
 6   UF                     1515040 non-null  object
 7   Nome UF                1515040 non-null  object
 8   Região                 1515040 non-null  object
 9   Código Nacional        1515040 non-null  float64
 10  % moradores cobertos   1513680 non-null  float64
 11  % domicílios cobertos  1513680 non-null  float64
 12  % área coberta         1513680 non-null  float64
dtypes: float64(7), object(6)
memory usage: 150.3+ MB

In [107]:
pd.DataFrame(df.groupby(['Operadora','Tecnologia']).agg({
    '% moradores cobertos':'mean',
    '% domicílios cobertos':'mean',
    '% área coberta':'mean'
})).head(30)

                      % moradores cobertos  % domicílios cobertos  \
Operadora Tecnologia
ALGAR     2G                      1.190191               1.190218
          3G                      1.739066               1.740096
          3G4G                    0.512496               0.512752
          4G                      1.079438               1.077552
          4G5G                    1.114331               1.113439
          5G                      0.168676               0.168495
          5G_SA_NSA               0.064326               0.064239
          Todas                   1.891669               1.891964
CLARO     2G                     47.257169              47.829535
          3G                     53.139028              53.733603
          3G4G                   14.652462              14.778928
          4G                     59.638477              60.036319
          4G5G                   48.469663              48.791409
          5G                      2.448571               2.457082
          5G_SA_NSA               1.169076               1.173032
          Todas                  64.663357              65.136839
LIGUE     2G                      0.007611               0.007885
          3G                      0.009058               0.009348
          3G4G                    0.005365               0.005508
          4G                      0.052418               0.052901
          4G5G                    0.047053               0.047393
          5G                      0.000000               0.000000
          5G_SA_NSA               0.000000               0.000000
          Todas                   0.052418               0.052901
NEXTEL    2G                      7.056285               7.082215
          3G                     16.813131              16.975671
          3G4G                    8.468471               8.549130
          4G                      6.751410               6.767088
          4G5G                    3.376103               3.383934
          5G                      0.000000               0.000000

                      % área coberta
Operadora Tecnologia
ALGAR     2G                0.344968
          3G                0.329953
          3G4G              0.154146
          4G                0.416921
          4G5G              0.443386
          5G                0.035442
          5G_SA_NSA         0.006073
          Todas             0.652517
CLARO     2G               13.202492
          3G               16.663517
          3G4G              6.313712
          4G               31.428342
          4G5G             26.496245
          5G                1.208162
          5G_SA_NSA         0.509281
          Todas            33.442258
LIGUE     2G                0.000180
          3G                0.000303
          3G4G              0.000239
          4G                0.013125
          4G5G              0.012886
          5G                0.000000
          5G_SA_NSA         0.000000
          Todas             0.013125
NEXTEL    2G                3.159836
          3G                6.793202
          3G4G              3.509828
          4G                3.799670
          4G5G              1.899980
          5G                0.000000

In [103]:
wow = df[
    (df['Tecnologia'] == '2G') & (df['Operadora'] == 'ALGAR')
]['% moradores cobertos']

wow = wow / 100
wow.mean()

0.011901912670293344

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

tree = DecisionTreeRegressor(max_depth=30, ccp_alpha=0)

grid_search = GridSearchCV(estimator=tree, 
                          param_grid=param_grid,
                          cv=5,  # 5-fold cross-validation
                          scoring='neg_mean_squared_error')  # Metrica de avaliação